// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['bindings']['ColumnBinding']['Create'](arg1);
}

export function Delete(arg1, arg2) {
  return window['go']['bindings']['ColumnBinding']['Delete'](arg1, arg2);
}

export function GetAll(arg1) {
  return window['go']['bindings']['ColumnBinding']['GetAll'](arg1);
}

export function Update(arg1) {
  return window['go']['bindings']['ColumnBinding']['Update'](arg1);
}
