// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Create(arg1:models.ColumnRequest):Promise<void>;

export function Delete(arg1:string,arg2:string):Promise<void>;

export function GetAll(arg1:string):Promise<models.Table>;

export function Update(arg1:models.ColumnRequest):Promise<void>;
