// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Create(arg1:models.ConnectionConfig):Promise<void>;

export function GetAll():Promise<Array<models.ConnectionConfig>>;
