// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAll() {
  return window['go']['bindings']['DatabaseBinding']['GetAll']();
}

export function Select(arg1) {
  return window['go']['bindings']['DatabaseBinding']['Select'](arg1);
}
