// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['bindings']['DatabaseBinding']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['bindings']['DatabaseBinding']['Delete'](arg1);
}

export function GetAll() {
  return window['go']['bindings']['DatabaseBinding']['GetAll']();
}

export function Select(arg1) {
  return window['go']['bindings']['DatabaseBinding']['Select'](arg1);
}

export function Update(arg1) {
  return window['go']['bindings']['DatabaseBinding']['Update'](arg1);
}
