// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetAll():Promise<models.DatabaseResponse>;

export function Select(arg1:string):Promise<void>;
