// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Create(arg1:models.ItemRequest):Promise<void>;

export function Delete(arg1:models.ItemRequest):Promise<void>;

export function GetAll(arg1:string):Promise<models.TableData>;

export function Update(arg1:models.ItemRequest):Promise<void>;
