// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['bindings']['ItemBinding']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['bindings']['ItemBinding']['Delete'](arg1);
}

export function GetAll(arg1) {
  return window['go']['bindings']['ItemBinding']['GetAll'](arg1);
}

export function Update(arg1) {
  return window['go']['bindings']['ItemBinding']['Update'](arg1);
}
