// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Active() {
  return window['go']['bindings']['SessionBinding']['Active']();
}

export function Connect(arg1) {
  return window['go']['bindings']['SessionBinding']['Connect'](arg1);
}
