// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['bindings']['TableBinding']['Create'](arg1);
}

export function GetAll() {
  return window['go']['bindings']['TableBinding']['GetAll']();
}

export function Update(arg1, arg2) {
  return window['go']['bindings']['TableBinding']['Update'](arg1, arg2);
}
