// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/connection": {
            "get": {
                "description": "Retorna todas as conexões cadastradas",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "connection"
                ],
                "summary": "Lista conexões salvas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ConnectionConfig"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "connection"
                ],
                "summary": "Altera conexão",
                "parameters": [
                    {
                        "description": "Dados da conexão",
                        "name": "connection",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ConnectionConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respond.Response"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "connection"
                ],
                "summary": "Salva conexão",
                "parameters": [
                    {
                        "description": "Dados da conexão",
                        "name": "connection",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ConnectionConfig"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/respond.Response"
                        }
                    }
                }
            }
        },
        "/connection/active": {
            "get": {
                "description": "Retorna a conexão ativa",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "connection"
                ],
                "summary": "Conexão ativa",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ConnectionResponse"
                        }
                    }
                }
            }
        },
        "/connection/connect": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "connection"
                ],
                "summary": "Faz a conexão",
                "parameters": [
                    {
                        "description": "Dados da conexão",
                        "name": "connection",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ConnectionConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ConnectionResponse"
                        }
                    }
                }
            }
        },
        "/connection/disconnect": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "connection"
                ],
                "summary": "Desfaz a conexão",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/connection/{id}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "connection"
                ],
                "summary": "Remove conexão",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da conexão",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respond.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/respond.Response"
                        }
                    }
                }
            }
        },
        "/database/select": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "database"
                ],
                "summary": "Seleciona um banco de dados",
                "parameters": [
                    {
                        "description": "Banco de Dados",
                        "name": "database",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DatabaseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/query": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "query"
                ],
                "summary": "Executa query",
                "parameters": [
                    {
                        "description": "Dados da query",
                        "name": "connection",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.QueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/respond.Response"
                        }
                    }
                }
            }
        },
        "/tables": {
            "get": {
                "description": "Retorna todas as tabelas do banco selecionado",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tables"
                ],
                "summary": "Lista de tabelas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ConnectionConfig": {
            "type": "object",
            "properties": {
                "database": {
                    "type": "string",
                    "example": ""
                },
                "driver": {
                    "type": "string",
                    "example": "mysql"
                },
                "host": {
                    "type": "string",
                    "example": "127.0.0.1"
                },
                "id": {
                    "type": "string",
                    "example": ""
                },
                "name": {
                    "type": "string",
                    "example": ""
                },
                "password": {
                    "type": "string",
                    "example": "senha123"
                },
                "port": {
                    "type": "integer",
                    "example": 3306
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "models.ConnectionResponse": {
            "type": "object",
            "properties": {
                "database": {
                    "type": "string"
                },
                "databases": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "driver": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                }
            }
        },
        "models.DatabaseRequest": {
            "type": "object",
            "properties": {
                "database": {
                    "type": "string",
                    "example": "my_system"
                }
            }
        },
        "models.QueryRequest": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string"
                }
            }
        },
        "respond.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8181",
	BasePath:         "/api/",
	Schemes:          []string{},
	Title:            "Database Manager API",
	Description:      "API para gerenciamento de bancos de dados.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
