basePath: /api/
definitions:
  models.ConnectionConfig:
    properties:
      database:
        example: ""
        type: string
      driver:
        example: mysql
        type: string
      host:
        example: 127.0.0.1
        type: string
      id:
        example: ""
        type: string
      name:
        example: ""
        type: string
      password:
        example: senha123
        type: string
      port:
        example: 3306
        type: integer
      username:
        example: admin
        type: string
    type: object
  models.ConnectionResponse:
    properties:
      database:
        type: string
      databases:
        items:
          type: string
        type: array
      driver:
        type: string
      host:
        type: string
      id:
        type: string
      name:
        type: string
      port:
        type: integer
    type: object
  models.DatabaseRequest:
    properties:
      database:
        example: my_system
        type: string
    type: object
  models.ItemRequest:
    properties:
      key:
        additionalProperties: {}
        type: object
      table:
        type: string
      values:
        additionalProperties: {}
        type: object
    type: object
  models.QueryRequest:
    properties:
      query:
        type: string
    type: object
  models.TableData:
    properties:
      columns:
        items:
          type: string
        type: array
      rows:
        items:
          additionalProperties: {}
          type: object
        type: array
    type: object
  respond.Response:
    properties:
      data: {}
      error:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
host: localhost:8181
info:
  contact: {}
  description: API para gerenciamento de bancos de dados.
  title: Database Manager API
  version: "1.0"
paths:
  /connection:
    get:
      description: Retorna todas as conexões cadastradas
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ConnectionConfig'
      summary: Lista conexões salvas
      tags:
      - connection
    post:
      consumes:
      - application/json
      parameters:
      - description: Dados da conexão
        in: body
        name: connection
        required: true
        schema:
          $ref: '#/definitions/models.ConnectionConfig'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/respond.Response'
      summary: Salva conexão
      tags:
      - connection
    put:
      consumes:
      - application/json
      parameters:
      - description: Dados da conexão
        in: body
        name: connection
        required: true
        schema:
          $ref: '#/definitions/models.ConnectionConfig'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/respond.Response'
      summary: Altera conexão
      tags:
      - connection
  /connection/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID da conexão
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/respond.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/respond.Response'
      summary: Remove conexão
      tags:
      - connection
  /database/select:
    post:
      consumes:
      - application/json
      parameters:
      - description: Banco de Dados
        in: body
        name: database
        required: true
        schema:
          $ref: '#/definitions/models.DatabaseRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Seleciona um banco de dados
      tags:
      - database
  /query:
    post:
      consumes:
      - application/json
      parameters:
      - description: Dados da query
        in: body
        name: connection
        required: true
        schema:
          $ref: '#/definitions/models.QueryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/respond.Response'
      summary: Executa query
      tags:
      - query
  /session:
    delete:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/respond.Response'
      summary: Desfaz a conexão
      tags:
      - session
    get:
      description: Retorna a conexão ativa
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ConnectionResponse'
      summary: Conexão ativa
      tags:
      - session
    post:
      consumes:
      - application/json
      parameters:
      - description: Dados da conexão
        in: body
        name: connection
        required: true
        schema:
          $ref: '#/definitions/models.ConnectionConfig'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ConnectionResponse'
      summary: Faz a conexão
      tags:
      - session
  /tables:
    get:
      description: Retorna todas as tabelas do banco selecionado
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Lista de tabelas
      tags:
      - tables
  /tables/item:
    delete:
      description: Remove um item de uma tabela
      parameters:
      - description: Item
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/models.ItemRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TableData'
      summary: Remove item
      tags:
      - item
    post:
      consumes:
      - application/json
      description: Insere um item em uma tabela
      parameters:
      - description: Item novo
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/models.ItemRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/respond.Response'
      summary: Insere item
      tags:
      - item
    put:
      consumes:
      - application/json
      description: Altera um item em uma tabela
      parameters:
      - description: Item
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/models.ItemRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/respond.Response'
      summary: Altera item
      tags:
      - item
  /tables/item/{table}:
    get:
      description: Retorna uma lista com as colunas e uma com os itens
      parameters:
      - description: Tabela
        in: path
        name: table
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TableData'
      summary: Lista colunas e itens
      tags:
      - item
swagger: "2.0"
