basePath: /api/
definitions:
  models.Column:
    properties:
      autoIncrement:
        example: false
        type: boolean
      defaultValue:
        example: ""
        type: string
      length:
        example: 10
        type: integer
      name:
        example: teste
        type: string
      nullable:
        example: true
        type: boolean
      primary:
        example: false
        type: boolean
      type:
        example: INT
        type: string
      unique:
        example: true
        type: boolean
    type: object
  models.ColumnRequest:
    properties:
      column:
        $ref: '#/definitions/models.Column'
      oldName:
        type: string
      table:
        type: string
    type: object
  models.ConnectionConfig:
    properties:
      database:
        example: ""
        type: string
      databases:
        items:
          type: string
        type: array
      driver:
        example: mysql
        type: string
      host:
        example: 127.0.0.1
        type: string
      id:
        example: ""
        type: string
      name:
        example: ""
        type: string
      password:
        example: senha123
        type: string
      port:
        example: 3306
        type: integer
      username:
        example: admin
        type: string
    type: object
  models.ConnectionResponse:
    properties:
      database:
        type: string
      databases:
        items:
          type: string
        type: array
      driver:
        type: string
      host:
        type: string
      id:
        type: string
      name:
        type: string
      port:
        type: integer
    type: object
  models.DatabaseRequest:
    properties:
      name:
        example: my_system
        type: string
      newName:
        example: db_teste1
        type: string
      oldName:
        example: db_teste
        type: string
    type: object
  models.ItemRequest:
    properties:
      key:
        additionalProperties: {}
        type: object
      table:
        type: string
      values:
        additionalProperties: {}
        type: object
    type: object
  models.QueryRequest:
    properties:
      query:
        type: string
    type: object
  models.Table:
    properties:
      columns:
        items:
          $ref: '#/definitions/models.Column'
        type: array
      name:
        example: teste
        type: string
    type: object
  models.TableData:
    properties:
      columns:
        items:
          type: string
        type: array
      rows:
        items:
          additionalProperties: {}
          type: object
        type: array
    type: object
  respond.Response:
    properties:
      data: {}
      error:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
host: localhost:8181
info:
  contact: {}
  description: API para gerenciamento de bancos de dados.
  title: Database Manager API
  version: "1.0"
paths:
  /connection:
    get:
      description: Retorna todas as conexões cadastradas
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ConnectionConfig'
      summary: Lista conexões salvas
      tags:
      - connection
    post:
      consumes:
      - application/json
      parameters:
      - description: Dados da conexão
        in: body
        name: connection
        required: true
        schema:
          $ref: '#/definitions/models.ConnectionConfig'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/respond.Response'
      summary: Salva conexão
      tags:
      - connection
    put:
      consumes:
      - application/json
      parameters:
      - description: Dados da conexão
        in: body
        name: connection
        required: true
        schema:
          $ref: '#/definitions/models.ConnectionConfig'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/respond.Response'
      summary: Altera conexão
      tags:
      - connection
  /connection/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID da conexão
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/respond.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/respond.Response'
      summary: Remove conexão
      tags:
      - connection
  /database:
    get:
      consumes:
      - application/json
      description: Retorna todas os bancos de dados
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Lista de banco de dados
      tags:
      - database
    post:
      consumes:
      - application/json
      description: Cria um banco de dados
      parameters:
      - description: Banco de Dados
        in: body
        name: database
        required: true
        schema:
          $ref: '#/definitions/models.DatabaseRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
      summary: Cria banco de dados
      tags:
      - database
    put:
      consumes:
      - application/json
      description: Altera um banco de dados
      parameters:
      - description: Banco de Dados
        in: body
        name: database
        required: true
        schema:
          $ref: '#/definitions/models.DatabaseRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Altera banco de dados
      tags:
      - database
  /database/select:
    post:
      consumes:
      - application/json
      parameters:
      - description: Banco de Dados
        in: body
        name: database
        required: true
        schema:
          $ref: '#/definitions/models.DatabaseRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Seleciona um banco de dados
      tags:
      - database
  /query:
    post:
      consumes:
      - application/json
      parameters:
      - description: Dados da query
        in: body
        name: connection
        required: true
        schema:
          $ref: '#/definitions/models.QueryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/respond.Response'
      summary: Executa query
      tags:
      - query
  /session:
    delete:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/respond.Response'
      summary: Desfaz a conexão
      tags:
      - session
    get:
      description: Retorna a conexão ativa
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ConnectionResponse'
      summary: Conexão ativa
      tags:
      - session
    post:
      consumes:
      - application/json
      parameters:
      - description: Dados da conexão
        in: body
        name: connection
        required: true
        schema:
          $ref: '#/definitions/models.ConnectionConfig'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ConnectionResponse'
      summary: Faz a conexão
      tags:
      - session
  /table:
    get:
      description: Retorna todas as tabelas do banco selecionado
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Lista de tabelas
      tags:
      - table
    post:
      consumes:
      - application/json
      description: Cria uma tabela
      parameters:
      - description: Tabela nova
        in: body
        name: tabela
        required: true
        schema:
          $ref: '#/definitions/models.Table'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/respond.Response'
      summary: Cria tabela
      tags:
      - table
  /table/{name}:
    delete:
      consumes:
      - application/json
      description: Remove o banco de dados
      parameters:
      - description: Nome da tabela
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/respond.Response'
      summary: Remove o banco de dados
      tags:
      - table
  /table/{oldName}/{newName}:
    put:
      consumes:
      - application/json
      description: Altera uma tabela
      parameters:
      - description: Nome atual
        in: path
        name: oldName
        required: true
        type: string
      - description: Nome novo
        in: path
        name: newName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/respond.Response'
      summary: Altera tabela
      tags:
      - table
  /table/{table}:
    delete:
      consumes:
      - application/json
      description: Remove uma tabela
      parameters:
      - description: Nome da tabela
        in: path
        name: table
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/respond.Response'
      summary: Remove tabela
      tags:
      - table
  /table/column:
    post:
      consumes:
      - application/json
      description: Cria uma coluna em uma tabela
      parameters:
      - description: Coluna novo
        in: body
        name: column
        required: true
        schema:
          $ref: '#/definitions/models.ColumnRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/respond.Response'
      summary: Cria coluna
      tags:
      - column
    put:
      consumes:
      - application/json
      description: Altera uma coluna em uma tabela
      parameters:
      - description: Coluna
        in: body
        name: column
        required: true
        schema:
          $ref: '#/definitions/models.ColumnRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/respond.Response'
      summary: Altera coluna
      tags:
      - column
  /table/column/{table}:
    get:
      description: Retorna uma lista com as colunas e o schema de uma tabela
      parameters:
      - description: Tabela
        in: path
        name: table
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Table'
      summary: Listar colunas de uma tabela
      tags:
      - column
  /table/column/{table}/{column}:
    delete:
      description: Remove uma coluna de uma tabela
      parameters:
      - description: Tabela
        in: path
        name: table
        required: true
        type: string
      - description: Coluna
        in: path
        name: column
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/respond.Response'
      summary: Remove coluna
      tags:
      - column
  /table/item:
    delete:
      description: Remove um item de uma tabela
      parameters:
      - description: Item
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/models.ItemRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TableData'
      summary: Remove item
      tags:
      - item
    post:
      consumes:
      - application/json
      description: Cria um item em uma tabela
      parameters:
      - description: Item novo
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/models.ItemRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/respond.Response'
      summary: Cria item
      tags:
      - item
    put:
      consumes:
      - application/json
      description: Altera um item em uma tabela
      parameters:
      - description: Item
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/models.ItemRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/respond.Response'
      summary: Altera item
      tags:
      - item
  /table/item/{table}:
    get:
      description: Retorna uma lista com as colunas e uma com os itens
      parameters:
      - description: Tabela
        in: path
        name: table
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TableData'
      summary: Lista colunas e itens
      tags:
      - item
  /version:
    get:
      description: Retorna a versão
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Obtem a versão
      tags:
      - app
swagger: "2.0"
